---
- name: Install Squid
  package:
    name: squid

- name: Configure Squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    validate: squid -k parse -f %s
  notify: Restart Squid
